# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-20 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_add_on_demand_is_avalilable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='on_demand_is_available',
            field=models.BooleanField(default=False),
        ),
    ]
